[project]
name = "wcsim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.15.15",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "F", "B"]

[tool.ruff.format]
docstring-code-format = true
