[project]
name = "wcsim"
version = "0.1.0"
description = "Simple Monte Carlo simulator for the 2026 World Cup"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tqdm>=4.68.2",
]
authors = [
    { name = "Florian Kéruzoré", email = "florian.keruzore@gmail.com" },
]

[dependency-groups]
dev = [
    "ruff>=0.15.15",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "F", "B"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pycodestyle]
max-doc-length = 72  # For docstrings and comments

